rootProject.name = "codejune-java"

include("codejune-core")
include("codejune-excel")
include("codejune-ftp")
include("codejune-http")
include("codejune-jdbc")
include("codejune-service")
include("codejune-shell")
include("codejune-webauto")
include("codejune-xml")
include("codejune-pool")
include("codejune-json")
include("codejune-redis")
include("codejune-websocket")
include("codejune-javascript")
include("codejune-socket")
include("codejune-javafx")
include("codejune-ocr")
include("codejune-tool")
include("codejune-uiauto")